spring:
  thymeleaf:
    cache: false
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  file:
    path: C:\Users\Administrator\IdeaProjects\springsecurity\
  level:
    com.example.mapper: debug
    org.springframework.security: info


server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml